version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_cc_sales
      - name: product
        identifier: raw_cc_stock
      - name: ship
        identifier: raw_cc_parcel